FROM python:3.9.10-slim

RUN python -m pip install mkdocs --upgrade

RUN python -m pip install mkdocs-material mkdocs-pdf-export-plugin weasyprint --upgrade

USER nobody
CMD cd /tmp/docs && mkdocs build
