ros2_to_zenoh:
  - ros_topic: "/ros2_chatter"
    zenoh_key: "62/ros2_chatter/**"
    msg_type: "std_msgs/msg/String"
  - ros_topic: "/cmd_vel"
    zenoh_key: "62/cmd_vel/**"
    msg_type: "geometry_msgs/msg/Twist"

zenoh_to_ros2:
  - zenoh_key: "62/zenoh_chatter/**"
    ros_topic: "/zenoh_chatter"
    msg_type: "std_msgs/msg/String"
  - zenoh_key: "62/voltage/**"
    ros_topic: "/voltage"
    msg_type: "std_msgs/msg/Float32"
  - zenoh_key: "62/imu/data_raw/**"
    ros_topic: "/imu/data_raw"
    msg_type: "sensor_msgs/msg/Imu"
  - zenoh_key: "62/vel_raw/**"
    ros_topic: "/vel_raw"
    msg_type: "geometry_msgs/msg/Twist"
  - zenoh_key: "62/cmd_vel/**"
    ros_topic: "/cmd_vel"
    msg_type: "geometry_msgs/msg/Twist"
