FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    aspell \
    aspell-en \
    python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /mnt

ENTRYPOINT ["/bin/bash", "-c"]
